book/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url 
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'book'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^book/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^book/content/(?P<pk>[0-9]+)/$', views.content, name='content'),
	url(r'^book/add_book/$', views.add_book, name='add_book'),
	url(r'^book/mulu/(?P<pk>[0-9]+)/$', views.mulu, name='mulu'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fangji/urls.py
from django.conf.urls import url 
from . import views

app_name = 'fangji'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^add_fangji/$', views.add_fangji, name='add_fangji'),
]

zhongyi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('book.urls')),
    url(r'doctor/', include('doctor.urls')),
    url(r'zhongyao/', include('zhongyao.urls')),
    url(r'fangji/', include('fangji.urls')),
]

book/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import markdown
from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.utils.html import strip_tags



@python_2_unicode_compatible
class Mulu(models.Model):
	name = models.CharField(verbose_name='目录', max_length=100)

	def __str__(self):
		return self.name





@python_2_unicode_compatible
class Book(models.Model):
	name = models.CharField(verbose_name='书名', max_length=100)
	mulu = models.ForeignKey(Mulu)
	created_time = models.DateTimeField(verbose_name='时间', null=True)
	author = models.CharField(verbose_name='作者', max_length=100)
	bookface = models.ImageField(upload_to='bookface', null=True, blank=True)
	content = models.TextField(verbose_name='内容')
	excerpt = models.CharField(verbose_name='摘要', max_length=200, blank=True)
	views = models.PositiveIntegerField(verbose_name='阅读量', default=0)




	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('book:detail', kwargs={'pk': self.pk}) 

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		# 如果没有写摘要
		if not self.excerpt:
			# 首先实例化一个 Markdown 类，用于渲染 body 的文本
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
			])
			# 先将 Markdown 文本渲染成 HTML 文本
			# strip_tags 去掉 HTML 文本的全部 HTML 标签
			# 从文本摘取前 54 个字符赋给 excerpt
			self.excerpt = strip_tags(md.convert(self.content))[:54]

		# 调用父类的 save 方法将数据保存到数据库中
		super(Book, self).save(*args, **kwargs)


	class Meta:
		verbose_name = '书籍'
		verbose_name_plural = '书籍列表'








@python_2_unicode_compatible
class Book_chapter(models.Model):
	name = models.CharField(verbose_name='章节名', max_length=140)
	book = models.ForeignKey('Book')
	# book_name = models.ForeignKey('Book', related_name='name', verbose_name='所属图书')
	created_time = models.DateTimeField(verbose_name='时间')
	content = models.TextField(verbose_name='内容')


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('book:content', kwargs={'pk': self.pk})

	class Meta:
		verbose_name = '图书章节'
		verbose_name_plural = '图书章节列表'

book/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Book

class BookForm(forms.ModelForm):

	class Meta:
		model = Book
		exclude = ("id", "created_time", "excerpt", "views",)

book/views.py
# -*- coding: utf-8 -*-

import markdown
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Book, Book_chapter, Mulu
from .forms import BookForm

def index(request):
	book_list = Book.objects.all().order_by('-created_time')

	paginator = Paginator(book_list, 2) #每页显示5个联系人

	page = request.GET.get('page', 1)
	try:
		book_list = paginator.page(page)
	except PageNotAnInteger:
		# 如果用户请求的页码号不是整数，显示第一页
		book_list = paginator.page(1)
	except EmptyPage:
		book_list = paginator.page(paginator.num_pages)

	return render(request, 'book/index.html', context={'book_list':book_list})










def detail(request, pk):
	book = get_object_or_404(Book, pk=pk)
	
	# 阅读量+1
	book.increase_views()

	book.content = markdown.markdown(book.content, extensions=[
																										'markdown.extensions.extra',
																										'markdown.extensions.codehilite',
																										'markdown.extensions.toc'
																								])

	book_chapter_list = book.book_chapter_set.all() 
	context = {'book':book, 'book_chapter_list':book_chapter_list}
	return render(request, 'book/detail.html', context=context)



def content(request, pk):
	book_chapter = get_object_or_404(Book_chapter, pk=pk)
	book_chapter.content = markdown.markdown(book_chapter.content, extensions=[
																										'markdown.extensions.extra',
																										'markdown.extensions.codehilite',
																										'markdown.extensions.toc'
																								])
	context = {'book_chapter':book_chapter, 'book_chapter.content':book_chapter.content}
	return render(request, 'book/content.html', context=context)



def add_book(request):
	if request.method == "POST":
		book_form = BookForm(request.POST)
		if book_form.is_valid():
			book_form.save()
			return HttpResponse("添加图书信息成功！")
	else:
		book_form = BookForm()
	return render(request, 'book/add_book.html', locals())





def mulu(request, pk):
	mulu = get_object_or_404(Mulu, pk=pk)
	book_list = Book.objects.filter(mulu=mulu).order_by('-created_time')
	return render(request, 'book/index.html', context={'book_list':book_list})

templates/book/add_book.html
{% extends 'base.html' %}

{% block main %}

		<h1>添加图书信息</h1>

		<form action="{% url 'book:add_book' %}" method="post">
			{% csrf_token %}
			{{ book_form.as_p }}
			<input type="submit" value="提交"><br>
		</form>


{% endblock main %}

templates/book/content.html
{% extends 'base.html' %}

{% block main %}

	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'fangji:index' %}">首页</a></li>
		  <li><a href="{% url 'book:index' %}">医书</a></li>
		  <li><a href="{{ book_chapter.book.get_absolute_url }}">{{ book_chapter.book }}</a></li>
		  <li class="active">{{ book_chapter.name }}</li>
		</ol>
	</div>

<!-- <head>
	<meta charset="UTF-8">
	<title>{{ book_chpater.name }} - 中医助手</title>
</head> -->

	<h1 class="name">
		{{ book_chapter.name }}
	</h1>
	<br>
	<span>书籍:<a href="{{ book_chapter.book.get_absolute_url }}">{{ book_chapter.book }}</a></span><br>
	<span>作者:{{ book_chapter.book.author }}</span>
	<br><br>
	<div class="content">
		{{ book_chapter.content|safe }}
	</div>

{% endblock main %}

templates/book/detail.html
{% extends 'base.html' %}

{% block main %}
	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'fangji:index' %}">首页</a></li>
		  <li><a href="{% url 'book:index' %}">医书</a></li>
		  <li class="active">{{ book.name }}</li>
		</ol>
	</div>


	<h1 class="name">
		{{ book.name }}
	</h1>
	<br>
	<div class="row">
	  <div class="col-xs-6 col-md-3">
	      <img src="/upload/{{ book.bookface }}" alt="{{ book.name }}" style="width:134px;height:180px;">
	  </div>
	  <div class="col-xs-6 col-md-3">
			<span>分类:{{ book.mulu }}</span><br>
			<span>作者:{{ book.author }}</span><br>
			<span class="views-count">阅读量：{{ book.views }}</span>
	  </div>
	  <div class="col-xs-6 col-md-3">
	    <a href="#" class="thumbnail">
	      医生作者图片
	    </a>
	  </div>
	  <div class="col-xs-6 col-md-3">
	    <a href="#" class="thumbnail">
	      其他
	    </a>
	  </div>
	</div>

	<br><br>
	<div class="content">
		{{ book.content|safe }}
	</div>
	<div class="chapter">
		{% for book_chapter in  book_chapter_list %}
		<ul class="chapter-list">
			<li class="chapter-item">
				<a href="{{ book_chapter.get_absolute_url }}">{{ book_chapter.name }}</a>
			</li>
		</ul>
		{% endfor %}
	</div>


{% endblock main %}

templates/book/index.html
{% extends 'base.html' %}
{% load book_tags %}

{% block main %}
	<h1>中医书籍</h1>
	<p>备注：</p>
	<br><br>


	<div class="widget widget-category">
		<strong class="widget-title">分类:</strong>
		{% get_mulus as mulu_list %}
		<ul style="display: block;margin-top: -20px;">
			{% for mulu in mulu_list %}
			<li style="display:inline-block;">
				<a href="{% url 'book:mulu' mulu.pk %}">{{ mulu.name }}</a>
			</li>
			{% empty %}
	    暂无分类
			{% endfor %}
		</ul>
	</div>
<br><br>

	{% for book in book_list %}
		<article class="book">
			<h3 class="name">
				<a href="{{ book.get_absolute_url }}">{{ book.name }}</a>
			</h3>
			<span class="views-count">{{ book.views }} 阅读</span>
      <p>{{ book.excerpt }} ...</p>
      <div class="read-more">
          <a href="{{ book.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
      </div>
		</article>
	{% empty %}
  	<div class="no-book">暂时还没有书籍</div>
  {% endfor %}

<br><br><br>

{% include 'pagination.html' %}




{% endblock main %}