book/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url 
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'book'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^book/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^book/content/(?P<pk>[0-9]+)/$', views.content, name='content'),
	url(r'^book/add_book/$', views.add_book, name='add_book'),
	url(r'^book/mulu/(?P<pk>[0-9]+)/$', views.mulu, name='mulu'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.conf.urls import url 
from . import views

app_name = 'doctor'
urlpatterns = [
	# url(r'^$', views.index, name='index'),
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DoctorDetailView.as_view(), name='detail'),
	url(r'^add_doctor/$', views.add_doctor, name='add_doctor'),

]

zhongyi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('book.urls')),
    url(r'doctor/', include('doctor.urls')),
    url(r'zhongyao/', include('zhongyao.urls')),
    url(r'fangji/', include('fangji.urls')),
]

doctor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible


@python_2_unicode_compatible
class Doctor(models.Model):
	name = models.CharField(verbose_name='医生姓名', max_length=100)
	province = models.CharField(verbose_name='省份', max_length=100)
	dynastic = models.CharField(verbose_name='朝代', max_length=100)
	doctorface = models.ImageField(upload_to='doctorface', null=True, blank=True)
	created_time = models.DateTimeField(verbose_name='添加时间', null=True)
	wiki = models.TextField(verbose_name='百科')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('doctor:detail', kwargs={'pk': self.pk})


	class Meta():
		verbose_name='名医'
		verbose_name_plural='名医列表'

doctor/forms.py
# -*- coding: utf-8 -*-
from django import forms

class DoctorForm(forms.Form):
	name = forms.CharField(label='医生姓名')
	province = forms.CharField(label='省份')
	dynastic = forms.CharField(label='朝代')
	wiki = forms.CharField(label='人物介绍')

	# name = forms.CharField(label='医生姓名', error_message={"required":"这项必须填写"})

doctor/views.py
# -*- coding: utf-8 -*-

import markdown
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Doctor
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from .forms import DoctorForm

# def index(request):
# 	doctor_list = Doctor.objects.all().order_by('-created_time')
# 	return render(request, 'doctor/index.html', context={'doctor_list':doctor_list})


class IndexView(ListView):
	model = Doctor
	template_name = 'doctor/index.html'
	context_object_name = 'doctor_list'
	# 指定 paginate_by 属性后开启分页功能， 其值代表每一页包含多少篇文章
	paginate_by = 5


# def detail(request, pk):
# 	doctor = get_object_or_404(Doctor, pk=pk)
# 	doctor.wiki = markdown.markdown(doctor.wiki, extensions=[
# 																										'markdown.extensions.extra',
# 																										'markdown.extensions.codehilite',
# 																										'markdown.extensions.toc'
# 																								])

# 	context = {'doctor':doctor}
# 	return render(request, 'doctor/detail.html', context=context)


class DoctorDetailView(DetailView):
	model = Doctor
	template_name = 'doctor/detail.html'
	context_object_name = 'doctor'


# 使用 Django Form 的情况
def add_doctor(request):
	if request.method == "POST":
		doctor_form = DoctorForm(request.POST)
		if doctor_form.is_valid():
			Doctor.objects.create(
				name = doctor_form.cleaned_data['name'],
				province = doctor_form.cleaned_data['province'],
				dynastic = doctor_form.cleaned_data['dynastic'],
				wiki = doctor_form.cleaned_data['wiki'],
			)
			return HttpResponse("添加医生信息成功。")
	else:
		doctor_form = DoctorForm()
		return render(request, 'doctor/add_doctor.html', locals())

templates/doctor/add_doctor.html
{% extends 'base.html' %}

{% block main %}

		<h1>添加医生信息</h1>

		<form action="{% url 'doctor:add_doctor' %}" method="post">
			{% csrf_token %}
			{{ doctor_form.as_p }}
			<input type="submit" value="提交"><br>
		</form>


{% endblock main %}

templates/doctor/detail.html
{% extends 'base.html' %}

{% block main %}
	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'book:index' %}">首页</a></li>
		  <li><a href="{% url 'doctor:index' %}">名医</a></li>
		  <li class="active">{{ doctor.name }}</li>
		</ol>
	</div>


	<h1 class="name">
		<a href="{{ doctor.get_absolute_url }}">{{ doctor.name }}</a> 
	</h1>
	<br>

	<div class="row">
	  <div class="col-xs-6 col-md-3">
	      <img src="/upload/{{ doctor.doctorface }}" alt="{{ doctor.name }}" style="width:134px;height:180px;">
	  </div>
	  <div class="col-xs-6 col-md-3">
			<span>省份:{{ doctor.province }}</span><br>
			<span>朝代:{{ doctor.dynastic }}</span>
	  </div>
	  <div class="col-xs-6 col-md-3">
	    <a href="#" class="thumbnail">
	      其他
	    </a>
	  </div>
	  <div class="col-xs-6 col-md-3">
	    <a href="#" class="thumbnail">
	      其他
	    </a>
	  </div>
	</div>


	<br><br>
	<div class="content">
		{{ doctor.wiki|safe }}
	</div>

{% endblock main %}

templates/doctor/index.html
{% extends 'base.html' %}

{% block main %}

	<h1>医生</h1>
	<p>备注：</p>
	<br><br>
	{% for doctor in doctor_list %}
		<article class="doctor">
			<h2 class="name">
				<a href="{{ doctor.get_absolute_url }}">{{ doctor.name }}</a>
			</h2>
			
		</article>
	{% empty %}
  	<div class="no-doctor">暂时还未填写名医</div>
  {% endfor %}


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}