book/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url 
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'book'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^book/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^book/content/(?P<pk>[0-9]+)/$', views.content, name='content'),
	url(r'^book/add_book/$', views.add_book, name='add_book'),
	url(r'^book/mulu/(?P<pk>[0-9]+)/$', views.mulu, name='mulu'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.conf.urls import url 
from . import views

app_name = 'doctor'
urlpatterns = [
	# url(r'^$', views.index, name='index'),
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DoctorDetailView.as_view(), name='detail'),
	url(r'^add_doctor/$', views.add_doctor, name='add_doctor'),

]

fangji/urls.py
from django.conf.urls import url 
from . import views

app_name = 'fangji'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^add_fangji/$', views.add_fangji, name='add_fangji'),
]

zhongyao/urls.py
from django.conf.urls import url 
from . import views

app_name = 'zhongyao'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

zhongyi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('book.urls')),
    url(r'doctor/', include('doctor.urls')),
    url(r'zhongyao/', include('zhongyao.urls')),
    url(r'fangji/', include('fangji.urls')),
]

templates/base.html
{% load staticfiles %}
{% load book_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>中医助手</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<style>
		.content-body{
			margin:0 30px;
		}
		.navbar-brand {
			margin-left: 20px;
		}
		
	</style>

</head>
<body>
	
	<nav class="navbar navbar-default navbar-static-top">
		<div class="navbar-header">
      <a class="navbar-brand" href="{% url 'book:index' %}">中医助手</a>
    </div>
	  <div class="container">
	    <p class="navbar-text navbar-right"><a href="{% url 'fangji:index' %}" class="navbar-link">方剂</a></p>
	    <p class="navbar-text navbar-right"><a href="{% url 'zhongyao:index' %}" class="navbar-link">中药</a></p>
	    <p class="navbar-text navbar-right"><a href="{% url 'doctor:index' %}" class="navbar-link">医生</a></p>
	    <p class="navbar-text navbar-right"><a href="{% url 'book:index' %}" class="navbar-link">书籍</a></p>
	  </div>
	</nav>


	<div class="content-body">
		<div class="row">
		
		  <div class="col-md-8">
				<div class="main">
					{% block main %}
			  	{% endblock main %}		
				</div>  	
		  </div>

		  <div class="col-md-4">
				  <div class="widget widget-recent-books">
					  <h3 class="widget-title">最新书籍</h3>
					  {% get_recent_books as recent_book_list %}
					  <ul>
					    {% for book in recent_book_list %}
					    <li>
					      <a href="{{ book.get_absolute_url }}">{{ book.name }}</a>
					    </li>

					    {% endfor %}
					  </ul>
					</div>
		  </div>

		</div>





	</div>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<footer style="margin-top:300px;text-align:center;">
	<p>底部</p>
</footer>

templates/pagination.html
  <div class="pagination-simple">
    {% if book_list.has_previous %}
      <a href="?page={{ book_list.previous_page_number }}">上一页</a>
    {% endif %}
    <span class="current">第 {{ book_list.number }} 页 / 共 {{ book_list.paginator.num_pages }} 页</span>
    <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
    {% if book_list.has_next %}
      <a href="?page={{ book_list.next_page_number }}">下一页</a>
    {% endif %}
  </div>