book/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url 
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'book'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^book/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^book/content/(?P<pk>[0-9]+)/$', views.content, name='content'),
	url(r'^book/add_book/$', views.add_book, name='add_book'),
	url(r'^book/mulu/(?P<pk>[0-9]+)/$', views.mulu, name='mulu'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fangji/urls.py
from django.conf.urls import url 
from . import views

app_name = 'fangji'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^add_fangji/$', views.add_fangji, name='add_fangji'),
]

zhongyi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('book.urls')),
    url(r'doctor/', include('doctor.urls')),
    url(r'zhongyao/', include('zhongyao.urls')),
    url(r'fangji/', include('fangji.urls')),
]

fangji/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Fangji(models.Model):
	name = models.CharField(verbose_name='方剂名', max_length=100)
	prescription = models.TextField(verbose_name='方剂组成')
	function = models.TextField(verbose_name='功能主治')
	dosage = models.TextField(verbose_name='剂量')
	taboo = models.TextField(verbose_name='禁忌')
	created_time = models.DateTimeField(verbose_name='添加时间', null=True)


	def __str__(self):
		return self.name;

	def get_absolute_url(self):
		return reverse('fangji:detail', kwargs={'pk': self.pk})


	class Meta:
		verbose_name = '方剂'
		verbose_name_plural = '方剂列表'

fangji/views.py
# -*- coding: utf-8 -*-

import markdown
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from .models import Fangji


def index(request):
	fangji_list = Fangji.objects.all().order_by('-created_time')

	paginator = Paginator(fangji_list, 2)
	page = request.GET.get('page')

	try:
		fangji_list = paginator.page(page)
	except PageNotAnInteger:
		fangji_list = paginator.page(1)
	except EmptyPage:
		fangji_list = paginator.page(paginator.num_pages)


	return render(request, 'fangji/index.html', context={'fangji_list':fangji_list})


def detail(request, pk):
	fangji = get_object_or_404(Fangji, pk=pk)
	fangji.prescription = markdown.markdown(fangji.prescription, extensions=[
																										'markdown.extensions.extra',
																										'markdown.extensions.codehilite',
																										'markdown.extensions.toc'
																								])
	fangji.function = markdown.markdown(fangji.function, extensions=[
																										'markdown.extensions.extra',
																										'markdown.extensions.codehilite',
																										'markdown.extensions.toc'
																								])

	fangji.dosage = markdown.markdown(fangji.dosage, extensions=[
																										'markdown.extensions.extra',
																										'markdown.extensions.codehilite',
																										'markdown.extensions.toc'
																								])
	context = {'fangji':fangji}
	return render(request, 'fangji/detail.html', context=context)


# 不知道为什么老出错：TemplateDoesNotExist at /fangji/add_fangji/
def add_fangji(request):
	if request.method == "POST":
		name = request.POST['name']
		prescription = request.POST['prescription']
		function = request.POST['function']
		dosage = request.POST['dosage']
		taboo = request.POST['taboo']
		# 然后把接收的数据放数据库里
		Fangji.objects.create(
			name = name,
			prescription = prescription,
			function = function,
			dosage = dosage,
			taboo = taboo,
		)
		return HttpResponse("添加方剂信息成功。")
	else:
		return render(request, 'fangji/add_fangji.html', locals())

templates/fangji/add_fangji.html
{% extends 'base.html' %}

{% block main %}

		<h1>添加方剂</h1>

		<form action="{% url 'fangji:add_fangji' %}" method="post">
			{% csrf_token %}
			方剂名：<input type="text" name="name"><br>
			方剂组成：<input type="text" name="prescription"><br>
			功能主治：<input type="text" name="function"><br>
			剂量：<input type="text" name="dosage"><br>
			禁忌：<input type="text" name="taboo"><br>
			<input type="submit" value="提交"><br>
		</form>


{% endblock main %}

templates/fangji/detail.html
{% extends 'base.html' %}

{% block main %}

<!-- <head>
	<meta charset="UTF-8">
	<title>{{ fangji.name }} - 方剂</title>
	<style>
		.fangji span {
			background-color: #ddd;
			padding: 2px 5px;
			border-left: 2px solid #666;
			margin-right: 1em;
		}
	</style>
</head> -->
	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'book:index' %}">首页</a></li>
		  <li><a href="{% url 'fangji:index' %}">方剂</a></li>
		  <li class="active">{{ fangji.name }}</li>
		</ol>
	</div>

	<h1 class="name">
		<a href="{{ fangji.get_absolute_url }}">{{ fangji.name }}</a> 
	</h1>
	<br>
	<div class="fangji">
		<p><span>药名:</span>{{ fangji.name }}</p>
		<p><span>处方:</span>{{ fangji.prescription|safe }}</p>
		<p><span>功能主治:</span>{{ fangji.function|safe }}</p>
		<p><span>禁忌:</span>{{ fangji.dosage|safe }}</p>
		<br><br>
	</div>

{% endblock main %}

templates/fangji/index.html
{% extends 'base.html' %}




{% block main %}

	<h1>方剂</h1>
	<p>备注：</p>
	<br><br>
	{% for fangji in fangji_list %}
		<article class="fangji">
			<h2 class="name">
				<a href="{{ fangji.get_absolute_url }}">{{ fangji.name }}</a>
			</h2>
			
		</article>
	{% empty %}
  	<div class="no-fangji">暂时无方剂</div>
  {% endfor %}


	<br><br><br>

	<div class="pagination-simple">
		{% if fangji_list.has_previous %}
			<a href="?page={{ fangji_list.previous_page_number }}">上一页</a>
		{% endif %}
		<span class="current">第 {{ fangji_list.number }} 页 / 共 {{ fangji_list.paginator.num_pages }} 页</span>
		<!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
		{% if fangji_list.has_next %}
			<a href="?page={{ fangji_list.next_page_number }}">下一页</a>
		{% endif %}
	</div>





{% endblock main %}